### ISSUE TITLE
jsonb_concat Aggregate Function?

### ISSUE THREAD

**Issue by vnnw** [erthalion/jsonbx#6]
I want to concatenate a json(b) column group by another column, but it is impossible to use the function 'jsonb_concat' to archive it.

for example:
   a | {'k1':1, 'k2':2} 
   a | {'k3':3}
   b | {'k1':1}

the aggregated result will be something like below:
  a | {'k1':1, 'k2':2, 'k3':3}
  b | {'k1':1}

Any possibility to create an such aggregation version of 'jsonb_concat'?

**Comment by vnnw** [comment]
Sorry, there is a json_object_agg already!
Thanks a million for your wonderful work!

**Comment by erthalion** [comment]
Yes, it's possible to aggregate jsonb data using the `json_object_agg` function (and if I remember correctly, there will be a function `jsonb_object_agg` in 9.5).

> Thanks a million for your wonderful work!

I'm glad to hear it, thanks =)
