### ISSUE TITLE
why this is error

### ISSUE THREAD

**Issue by lywaterman** [erthalion/jsonbx#7]
game=# select jsonb_set('{"a":1,"b":[0,1,2,3,4,5,6,7,8,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"c":{"d":1}}','{"b",-101}','123');
ERROR:  path element at the position 2 is not an integer

**Comment by lywaterman** [comment]
this is a random error, and i change 568:       char       *c = VARDATA_ANY(path_elems[level]); to
char       *c = TextDatumGetCString(path_elems[level]); because the strtol need a cstirng

**Comment by erthalion** [comment]
@lywaterman Yes, you're right - I missed, that `VARDATA_ANY` result isn't null-terminated, which is important for the `strtol`.
